// Code generated by gen (ddl projection). DO NOT EDIT.
// the schema is a projection too: CREATE TABLE per container, types and
// keys read straight off the grammar. one statement per container, in
// declaration order — the sqlite substrate the mesh converges onto.
package ddl

// Statements returns the DDL for every container. foreign keys are left
// off on purpose: a leaderless mesh applies rows in verified-time order,
// not dependency order, so referential integrity is eventual — the price
// of offline writes, named rather than hidden.
func Statements() []string {
	return []string{
		`CREATE TABLE IF NOT EXISTS "messages" (
  "mint" TEXT NOT NULL,
  "seq" INTEGER NOT NULL,
  "action_kind" TEXT,
  "created_at" TEXT NOT NULL,
  "inner_ix_idx" INTEGER NOT NULL,
  "memo_text" TEXT NOT NULL,
  "sender" TEXT NOT NULL,
  "signature" TEXT NOT NULL,
  "slot" INTEGER NOT NULL,
  PRIMARY KEY ("mint", "seq")
)`,
		`CREATE TABLE IF NOT EXISTS "meta" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  PRIMARY KEY ("key")
)`,
		`CREATE TABLE IF NOT EXISTS "notes" (
  "project" TEXT NOT NULL,
  "task_id" TEXT NOT NULL,
  "seq" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "sender" TEXT NOT NULL,
  "text" TEXT NOT NULL,
  PRIMARY KEY ("project", "task_id", "seq")
)`,
		`CREATE TABLE IF NOT EXISTS "tasks" (
  "project" TEXT NOT NULL,
  "id" TEXT NOT NULL,
  "accepted_by" TEXT NOT NULL,
  "brief" TEXT NOT NULL,
  "claimed_at" TEXT NOT NULL,
  "completed_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "funder" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "rejected_by" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY ("project", "id")
)`,
	}
}
