// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Message struct {
	Mint       string  `db:"mint"`
	Seq        int64   `db:"seq"`
	ActionKind *string `db:"action_kind"`
	CreatedAt  string  `db:"created_at"`
	InnerIxIdx int64   `db:"inner_ix_idx"`
	Memo       string  `db:"memo_text"`
	Sender     string  `db:"sender"`
	Signature  string  `db:"signature"`
	Slot       int64   `db:"slot"`
}

type MessageDomain interface {
	GetMessage(ctx context.Context, mint string, seq int64) *lazy.Lazy[Message]
	WindowMessageByMint(ctx context.Context, mint string, from int64, to int64, limit int32) *lazy.Lazy[Message]
	PageMessageByMint(ctx context.Context, mint string, after int64, limit int32) *lazy.Lazy[Message]
	InsertMessage(ctx context.Context, row Message) (*Message, error)
	DeleteMessage(ctx context.Context, mint string, seq int64) (*Message, error)
	UpdateMessage(ctx context.Context, row Message) (*Message, error)
}

type messageDomain struct{}

func NewMessageDomain() *messageDomain {
	return &messageDomain{}
}

func ScanMessage(row lazy.ScanRow) (Message, error) {
	var out Message
	err := row.Scan(
		&out.Mint,
		&out.Seq,
		&out.ActionKind,
		&out.CreatedAt,
		&out.InnerIxIdx,
		&out.Memo,
		&out.Sender,
		&out.Signature,
		&out.Slot,
	)
	return out, err
}

func (d *messageDomain) one(rows *sql.Rows) (*Message, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanMessage(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *messageDomain) GetMessage(ctx context.Context, mint string, seq int64) *lazy.Lazy[Message] {
	l := lazy.New(ScanMessage)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "mint", "seq", "action_kind", "created_at", "inner_ix_idx", "memo_text", "sender", "signature", "slot" FROM "messages" WHERE "mint" = $1 AND "seq" = $2`,
		mint,
		seq,
	)
	out, err := ScanMessage(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *messageDomain) WindowMessageByMint(ctx context.Context, mint string, from int64, to int64, limit int32) *lazy.Lazy[Message] {
	l := lazy.New(ScanMessage)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "mint", "seq", "action_kind", "created_at", "inner_ix_idx", "memo_text", "sender", "signature", "slot" FROM "messages" WHERE "mint" = $1 AND "seq" >= $2 AND "seq" < $3 ORDER BY "mint", "seq" LIMIT $4`,
		mint,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Message
	for rows.Next() {
		row, err := ScanMessage(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *messageDomain) PageMessageByMint(ctx context.Context, mint string, after int64, limit int32) *lazy.Lazy[Message] {
	l := lazy.New(ScanMessage)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "mint", "seq", "action_kind", "created_at", "inner_ix_idx", "memo_text", "sender", "signature", "slot" FROM "messages" WHERE "mint" = $1 AND "seq" > $2 ORDER BY "mint", "seq" LIMIT $3`,
		mint,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Message
	for rows.Next() {
		row, err := ScanMessage(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *messageDomain) InsertMessage(ctx context.Context, row Message) (*Message, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "messages" ("mint", "seq", "action_kind", "created_at", "inner_ix_idx", "memo_text", "sender", "signature", "slot") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "mint", "seq", "action_kind", "created_at", "inner_ix_idx", "memo_text", "sender", "signature", "slot"`,
		row.Mint,
		row.Seq,
		row.ActionKind,
		row.CreatedAt,
		row.InnerIxIdx,
		row.Memo,
		row.Sender,
		row.Signature,
		row.Slot,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *messageDomain) DeleteMessage(ctx context.Context, mint string, seq int64) (*Message, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "messages" WHERE "mint" = $1 AND "seq" = $2 RETURNING "mint", "seq", "action_kind", "created_at", "inner_ix_idx", "memo_text", "sender", "signature", "slot"`,
		mint,
		seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *messageDomain) UpdateMessage(ctx context.Context, row Message) (*Message, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "messages" SET "action_kind" = $1, "created_at" = $2, "inner_ix_idx" = $3, "memo_text" = $4, "sender" = $5, "signature" = $6, "slot" = $7 WHERE "mint" = $8 AND "seq" = $9 RETURNING "mint", "seq", "action_kind", "created_at", "inner_ix_idx", "memo_text", "sender", "signature", "slot"`,
		row.ActionKind,
		row.CreatedAt,
		row.InnerIxIdx,
		row.Memo,
		row.Sender,
		row.Signature,
		row.Slot,
		row.Mint,
		row.Seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
