// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Note struct {
	Project   string `db:"project"`
	TaskId    string `db:"task_id"`
	Seq       int64  `db:"seq"`
	CreatedAt string `db:"created_at"`
	Sender    string `db:"sender"`
	Text      string `db:"text"`
}

type NoteDomain interface {
	GetNote(ctx context.Context, project string, taskId string, seq int64) *lazy.Lazy[Note]
	WindowNoteByProjectTaskId(ctx context.Context, project string, taskId string, from int64, to int64, limit int32) *lazy.Lazy[Note]
	PageNoteByProjectTaskId(ctx context.Context, project string, taskId string, after int64, limit int32) *lazy.Lazy[Note]
	InsertNote(ctx context.Context, row Note) (*Note, error)
	DeleteNote(ctx context.Context, project string, taskId string, seq int64) (*Note, error)
	UpdateNote(ctx context.Context, row Note) (*Note, error)
}

type noteDomain struct{}

func NewNoteDomain() *noteDomain {
	return &noteDomain{}
}

func ScanNote(row lazy.ScanRow) (Note, error) {
	var out Note
	err := row.Scan(
		&out.Project,
		&out.TaskId,
		&out.Seq,
		&out.CreatedAt,
		&out.Sender,
		&out.Text,
	)
	return out, err
}

func (d *noteDomain) one(rows *sql.Rows) (*Note, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanNote(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *noteDomain) GetNote(ctx context.Context, project string, taskId string, seq int64) *lazy.Lazy[Note] {
	l := lazy.New(ScanNote)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "project", "task_id", "seq", "created_at", "sender", "text" FROM "notes" WHERE "project" = $1 AND "task_id" = $2 AND "seq" = $3`,
		project,
		taskId,
		seq,
	)
	out, err := ScanNote(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *noteDomain) WindowNoteByProjectTaskId(ctx context.Context, project string, taskId string, from int64, to int64, limit int32) *lazy.Lazy[Note] {
	l := lazy.New(ScanNote)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "project", "task_id", "seq", "created_at", "sender", "text" FROM "notes" WHERE "project" = $1 AND "task_id" = $2 AND "seq" >= $3 AND "seq" < $4 ORDER BY "project", "task_id", "seq" LIMIT $5`,
		project,
		taskId,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Note
	for rows.Next() {
		row, err := ScanNote(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *noteDomain) PageNoteByProjectTaskId(ctx context.Context, project string, taskId string, after int64, limit int32) *lazy.Lazy[Note] {
	l := lazy.New(ScanNote)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "project", "task_id", "seq", "created_at", "sender", "text" FROM "notes" WHERE "project" = $1 AND "task_id" = $2 AND "seq" > $3 ORDER BY "project", "task_id", "seq" LIMIT $4`,
		project,
		taskId,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Note
	for rows.Next() {
		row, err := ScanNote(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *noteDomain) InsertNote(ctx context.Context, row Note) (*Note, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "notes" ("project", "task_id", "seq", "created_at", "sender", "text") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "project", "task_id", "seq", "created_at", "sender", "text"`,
		row.Project,
		row.TaskId,
		row.Seq,
		row.CreatedAt,
		row.Sender,
		row.Text,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *noteDomain) DeleteNote(ctx context.Context, project string, taskId string, seq int64) (*Note, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "notes" WHERE "project" = $1 AND "task_id" = $2 AND "seq" = $3 RETURNING "project", "task_id", "seq", "created_at", "sender", "text"`,
		project,
		taskId,
		seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *noteDomain) UpdateNote(ctx context.Context, row Note) (*Note, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "notes" SET "created_at" = $1, "sender" = $2, "text" = $3 WHERE "project" = $4 AND "task_id" = $5 AND "seq" = $6 RETURNING "project", "task_id", "seq", "created_at", "sender", "text"`,
		row.CreatedAt,
		row.Sender,
		row.Text,
		row.Project,
		row.TaskId,
		row.Seq,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
