// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"
	"strconv"

	"github.com/mrsirg97-rgb/rig/v2/store/lazy"
	"github.com/mrsirg97-rgb/rig/v2/store/sqlx"
)

type ProjectSource struct {
	Project string `db:"project"`
	Source  string `db:"source"`
}

type ProjectSourceDomain interface {
	GetProjectSource(ctx context.Context, project string) *lazy.Lazy[ProjectSource]
	GetProjectSourceBatch(ctx context.Context, keys []string) *lazy.Lazy[ProjectSource]
	InsertProjectSource(ctx context.Context, row ProjectSource) (*ProjectSource, error)
	DeleteProjectSource(ctx context.Context, project string) (*ProjectSource, error)
	UpdateProjectSource(ctx context.Context, row ProjectSource) (*ProjectSource, error)
}

type projectSourceDomain struct{}

func NewProjectSourceDomain() *projectSourceDomain {
	return &projectSourceDomain{}
}

func ScanProjectSource(row lazy.ScanRow) (ProjectSource, error) {
	var out ProjectSource
	err := row.Scan(
		&out.Project,
		&out.Source,
	)
	return out, err
}

func (d *projectSourceDomain) one(rows *sql.Rows) (*ProjectSource, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanProjectSource(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *projectSourceDomain) GetProjectSource(ctx context.Context, project string) *lazy.Lazy[ProjectSource] {
	l := lazy.New(ScanProjectSource)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "project", "source" FROM "project_sources" WHERE "project" = $1`,
		project,
	)
	out, err := ScanProjectSource(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *projectSourceDomain) GetProjectSourceBatch(ctx context.Context, keys []string) *lazy.Lazy[ProjectSource] {
	l := lazy.New(ScanProjectSource)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	if len(keys) == 0 {
		l.FillAll(nil, nil)
		return l
	}
	// one numbered placeholder per key: portable across database/sql
	// drivers (postgres and sqlite alike); ANY($1) is postgres-only.
	ph := "$1"
	args := make([]any, len(keys))
	args[0] = keys[0]
	for i := 1; i < len(keys); i++ {
		ph += ", $" + strconv.Itoa(i+1)
		args[i] = keys[i]
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "project", "source" FROM "project_sources" WHERE "project" IN (`+ph+`)`, args...)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []ProjectSource
	for rows.Next() {
		row, err := ScanProjectSource(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *projectSourceDomain) InsertProjectSource(ctx context.Context, row ProjectSource) (*ProjectSource, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "project_sources" ("project", "source") VALUES ($1, $2) RETURNING "project", "source"`,
		row.Project,
		row.Source,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *projectSourceDomain) DeleteProjectSource(ctx context.Context, project string) (*ProjectSource, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "project_sources" WHERE "project" = $1 RETURNING "project", "source"`,
		project,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *projectSourceDomain) UpdateProjectSource(ctx context.Context, row ProjectSource) (*ProjectSource, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "project_sources" SET "source" = $1 WHERE "project" = $2 RETURNING "project", "source"`,
		row.Source,
		row.Project,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
