// Code generated by gen (domain projection). DO NOT EDIT.
package domain

import (
	"context"
	"database/sql"
	"errors"

	"github.com/mrsirg97-rgb/rig/store/lazy"
	"github.com/mrsirg97-rgb/rig/store/sqlx"
)

type Task struct {
	Project     string `db:"project"`
	Id          string `db:"id"`
	AcceptedBy  string `db:"accepted_by"`
	Brief       string `db:"brief"`
	ClaimedAt   string `db:"claimed_at"`
	CompletedAt string `db:"completed_at"`
	CreatedAt   string `db:"created_at"`
	Funder      string `db:"funder"`
	Owner       string `db:"owner"`
	RejectedBy  string `db:"rejected_by"`
	Status      string `db:"status"`
	Title       string `db:"title"`
	UpdatedAt   string `db:"updated_at"`
}

type TaskDomain interface {
	GetTask(ctx context.Context, project string, id string) *lazy.Lazy[Task]
	WindowTaskByProject(ctx context.Context, project string, from string, to string, limit int32) *lazy.Lazy[Task]
	PageTaskByProject(ctx context.Context, project string, after string, limit int32) *lazy.Lazy[Task]
	InsertTask(ctx context.Context, row Task) (*Task, error)
	DeleteTask(ctx context.Context, project string, id string) (*Task, error)
	UpdateTask(ctx context.Context, row Task) (*Task, error)
}

type taskDomain struct{}

func NewTaskDomain() *taskDomain {
	return &taskDomain{}
}

func ScanTask(row lazy.ScanRow) (Task, error) {
	var out Task
	err := row.Scan(
		&out.Project,
		&out.Id,
		&out.AcceptedBy,
		&out.Brief,
		&out.ClaimedAt,
		&out.CompletedAt,
		&out.CreatedAt,
		&out.Funder,
		&out.Owner,
		&out.RejectedBy,
		&out.Status,
		&out.Title,
		&out.UpdatedAt,
	)
	return out, err
}

func (d *taskDomain) one(rows *sql.Rows) (*Task, error) {
	defer rows.Close()
	if !rows.Next() {
		return nil, rows.Err()
	}
	out, err := ScanTask(rows)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (d *taskDomain) GetTask(ctx context.Context, project string, id string) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	row := tx.QueryRowContext(ctx,
		`SELECT "project", "id", "accepted_by", "brief", "claimed_at", "completed_at", "created_at", "funder", "owner", "rejected_by", "status", "title", "updated_at" FROM "tasks" WHERE "project" = $1 AND "id" = $2`,
		project,
		id,
	)
	out, err := ScanTask(row)
	if errors.Is(err, sql.ErrNoRows) {
		l.Fill(nil, nil)
		return l
	}
	if err != nil {
		l.Fill(nil, err)
		return l
	}
	l.Fill(&out, nil)
	return l
}

func (d *taskDomain) WindowTaskByProject(ctx context.Context, project string, from string, to string, limit int32) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "project", "id", "accepted_by", "brief", "claimed_at", "completed_at", "created_at", "funder", "owner", "rejected_by", "status", "title", "updated_at" FROM "tasks" WHERE "project" = $1 AND "id" >= $2 AND "id" < $3 ORDER BY "project", "id" LIMIT $4`,
		project,
		from, to, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Task
	for rows.Next() {
		row, err := ScanTask(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDomain) PageTaskByProject(ctx context.Context, project string, after string, limit int32) *lazy.Lazy[Task] {
	l := lazy.New(ScanTask)
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	rows, err := tx.QueryContext(ctx,
		`SELECT "project", "id", "accepted_by", "brief", "claimed_at", "completed_at", "created_at", "funder", "owner", "rejected_by", "status", "title", "updated_at" FROM "tasks" WHERE "project" = $1 AND "id" > $2 ORDER BY "project", "id" LIMIT $3`,
		project,
		after, limit,
	)
	if err != nil {
		l.FillAll(nil, err)
		return l
	}
	defer rows.Close()
	var out []Task
	for rows.Next() {
		row, err := ScanTask(rows)
		if err != nil {
			l.FillAll(nil, err)
			return l
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		l.FillAll(nil, err)
		return l
	}
	l.FillAll(out, nil)
	return l
}

func (d *taskDomain) InsertTask(ctx context.Context, row Task) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `INSERT INTO "tasks" ("project", "id", "accepted_by", "brief", "claimed_at", "completed_at", "created_at", "funder", "owner", "rejected_by", "status", "title", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING "project", "id", "accepted_by", "brief", "claimed_at", "completed_at", "created_at", "funder", "owner", "rejected_by", "status", "title", "updated_at"`,
		row.Project,
		row.Id,
		row.AcceptedBy,
		row.Brief,
		row.ClaimedAt,
		row.CompletedAt,
		row.CreatedAt,
		row.Funder,
		row.Owner,
		row.RejectedBy,
		row.Status,
		row.Title,
		row.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDomain) DeleteTask(ctx context.Context, project string, id string) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `DELETE FROM "tasks" WHERE "project" = $1 AND "id" = $2 RETURNING "project", "id", "accepted_by", "brief", "claimed_at", "completed_at", "created_at", "funder", "owner", "rejected_by", "status", "title", "updated_at"`,
		project,
		id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}

func (d *taskDomain) UpdateTask(ctx context.Context, row Task) (*Task, error) {
	tx, err := sqlx.TxFrom(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := tx.QueryContext(ctx, `UPDATE "tasks" SET "accepted_by" = $1, "brief" = $2, "claimed_at" = $3, "completed_at" = $4, "created_at" = $5, "funder" = $6, "owner" = $7, "rejected_by" = $8, "status" = $9, "title" = $10, "updated_at" = $11 WHERE "project" = $12 AND "id" = $13 RETURNING "project", "id", "accepted_by", "brief", "claimed_at", "completed_at", "created_at", "funder", "owner", "rejected_by", "status", "title", "updated_at"`,
		row.AcceptedBy,
		row.Brief,
		row.ClaimedAt,
		row.CompletedAt,
		row.CreatedAt,
		row.Funder,
		row.Owner,
		row.RejectedBy,
		row.Status,
		row.Title,
		row.UpdatedAt,
		row.Project,
		row.Id,
	)
	if err != nil {
		return nil, err
	}
	return d.one(rows)
}
